SSAFYnity/Job-Preparation-Challenge-5th

Programmers/디스크컨트롤러/디스크컨트롤러_채예은.py
#3 
처음엔 좀 어려워보였는데 풀고 나니 생각보다 어렵진 않았다.
힙을 사용하지 않고 생각나는대로 구현했다.
=> solved 디스크컨트롤러 - 40.83ms 10.4MB

Baekjoon/친구네트워크/친구네트워크_김수빈
#2 
어려웠다 처음에 무작정 다 bfs로 풀었는데 서로소 집합으로 개선하라는 이야기를 듣고 찾아보고 개산했다.
- union-find
=> solved 친구 네트워크 - 1600ms 101680kb

Programmers/디스크컨트롤러/디스크컨트롤러_김수빈.java
#3 
PriorityQueue 라이브러리를 잘 사용안해봐서 까먹었다.
- start, end 변수 이용
=> solved 디스크 컨트롤러 - 2.52ms 90.7mb

Programmers/부대복귀/부대복귀_옥수빈.java
=> solved 부대복귀 - 514.63ms 286mb

Baekjoon/색종이붙이기/색종이붙이기_옥수빈.java
=> solved 색종이 붙이기 - 168ms 19.484mb

Programmers/부대복귀/부대복귀_박단비.py
=> solved 부대복귀 - 617.05ms 106mb

Programmers/부대복귀/김범규_부대복귀.js
#1 
BFS를 이용해서 경로 계산 하였습니다
distance 배열에 목적지 기준 경로 길이를 저장해놓고, 이를 answer에 옮김
=> solved 부대복귀 9094.75ms 186mb

Baekjoon/친구네트워크/김범규_친구네트워크.java
=> solved 친구네트워크 1628ms 109088kb

Programmers/부대복귀/부대복귀_주혜련.cpp
#1 
쉬웠다
양방향 조건 -> 다익스트라 한번으로 dest에서 각 시작점 사이 최단거리 구할 수 있음
=> solved 부대복귀 - 117.71ms 107MB

Baekjoon/친구네트워크/친구네트워크_주혜련.java
#2 
쉬웠다
유니온 파인트. merge할 때 cnt도 함께 처리해주기
=> solved 친구네트워크 - 1488ms 85160KB

Programmers/부대복귀/부대복귀_허승경.java
#1 
괜찮았습니다.
- 각각의 지역 -> 목적지로 구하지 않고 목적지 -> 모든 지역의 거리 구하기
=> solved 부대복귀 - 224.14ms 196mb

Baekjoon/친구네트워크/허승경_친구네트워크.java
#2 
처음에 bfs로 풀다가 시간초과가 났습니다
유니온 파인드 개념을 몰라 시간이 조금 걸렸습니다
- 유니온 파인드
=> solved 친구네트워크 - 860ms 92.248mb

Baekjoon/친구네트워크/친구네트워크_박단비.py
=> solved 친구네트워크 - 276ms 62452kb

Programmers/디스크컨트롤러/허승경_디스크컨트롤러.java
#3 
람다식으로 정렬하는 걸 기억 해야 할 것 같습니다~
- jobs 배열 정렬
- PriorityQueue
=> solved 디스크컨트롤러 - 3.94ms 98.4mb

Baekjoon/색종이붙이기/허승경_색종이붙이기.java
#4 
아이디어를 생각해내는게 어려웠습니다.
처음에는 탐색문제인줄 알고 사방탐색으로 접근하려고 했지만, 정사각형처럼 깔끔하게 접근이 안되었습니다.
현재 위치를 정사각형의 왼쪽상단으로 잡고 가장 큰 색종이부터 붙일수 있는지를 확인하며
접근하는 백트래킹 문제였습니다
- 백트래킹
- 현재 위치를 정사각형의 왼쪽 상단으로 잡기
=> solved 색종이붙이기 372ms 26.396mb

Programmers/디스크컨트롤러/디스크컨트롤러_박단비.py
=> solved 디스크컨트롤러 - 0.57ms 10.4mb

Baekjoon/색종이붙이기/색종이붙이기_박단비.py
=> solved 색종이붙이기 - 2012ms 32544kb

Baekjoon/친구네트워크/친구네트워크_박주빈.cpp
#2 
어려웠습니다. Union-Find를 아예 떠올리지 못해 HashMap을 BFS를 통해 카운팅 했는데
시간초과가 계속 나서 검색을 해보니 다들 Union-Find를 사용했길래
구현 방법을 보고 고쳤더니 해결됐습니다.
Union-Find
없습니다.
=> solved 친구네트워크 - 224ms 19304kb

Programmers/디스크컨트롤러/디스크컨트롤러_박주빈.cpp
#3
적당한 난이도 였습니다.
시험공부를 하며 우선순위 큐에 대한 부분이 기억에 남아있어
구현방법에 대한 아이디어를 금방 떠올렸습니다.
- Sort
- Priority Queue
없습니다.
=> solved 디스크컨트롤러 - 0.64ms 4.2mb

Baekjoon/색종이붙이기/색종이붙이기_박주빈.cpp
#4 
적당한 난이도였습니다.
재귀함수를 이용해 모든 경우의 수를 탐색하는 식으로 구현하려고 했는데,
문제 난이도를 보니 그렇게 하면 당연히 시간초과가 날 것 같아서
백트래킹을 이용하여 재귀함수가 더 이상 돌지 않아도 되는 조건문으로 가지치기를 하여
필요한 연산의 수를 줄이는 방식으로 구현하였습니다.
- 백트래킹
- 완전 탐색
없습니다.
=> solved 색종이붙이기  - 40ms 2020kb

Programmers/파괴되지않은건물/파괴되지않은건물_박주빈.cpp
#89
어려웠습니다.
board 의 크기가 최대 1000*1000, skill도 최대 25만개까지 들어오기 때문에,
계속 순차탐색을 하며 더하는 방식으로는 시간초과가 날 것 같아서 조금 생각해보니
모든 skill을 먼저 합한 뒤 이후 한번만 탐색하는 누적합에 대한 아이디어는 금방 떠올렸습니다.
그런데 구현을 하면서 배열 인덱스를 계속 실수하여 이 부분에서 시간이 오래 걸렸습니다.
누적합
없습니다.
=> solved 파괴되지않은건물 - 35.94ms 115MB

Programmers/파일명정렬/파일명정렬_박주빈.cpp
#93 
쉬운 편이었습니다.
안정 정렬와 불안정 정렬에 대해 알고 있으면 주어진 조건에 맞게 정렬을 구현할 수 있었습니다.
Head와 Number가 같으면 들어온 순서를 유지해야 하기 때문에, 안정 정렬을 사용해야 합니다.
- 안정 정렬
없습니다.
=> solved 파일명정렬 - 1.32ms 4.21mb

Programmers/파일명정렬/파일명정렬_신유진.java
#93 
- 어렵지는 않았음
- 정규 표현식을 알지만 제대로는 쓸 줄 몰라 다시 공부
- 정규 표현식
- 정렬
- 정규 표현식 사용
- 첫번째 단어: 영어 대소문자, “.”, “-”, 공백 가능
⇒ `([a-zA-Z .-]+)` : 대괄호 안에 있는 것은 들어올 수 있는 문자 의미, “+”는 한번 이상 반복 의미, 소괄호는 그룹 의미
- 두번째 단어: 숫자만 가능
=> `(\\d+)` : 숫자가 하나 이상 있음.
- 세번째 단어: 영어 대소문자, “.”, “-”, 공백 가능
⇒ `([a-zA-Z0-9 .-]*)?` : 해당 문자들이 없을 수도 있고 1개 이상일 수도 있음. 그리고 이 그룹은 아예 없을 수도 있고 한 개만 있을 수 있음.
- 주어진 문자열을 해당 3부분으로 나누고 세번째 문자가 없다면 null 저장
- 첫번째 문자를 기준으로 정렬하고 이 값이 같다면 두번째 문자를 기준으로 문자가 5개 이상이면 5개까지만 잘라서 숫자로 만든 후 비교 후 정렬.
- 정렬한 값들을 다시 합쳐서 출력
=> solved 파일명 정렬 - 43.39ms 217mb

Programmers/파괴되지않은건물/파괴되지않은건물_신유진.java
#89 
- 어려웠음
- 블로그를 확인해서 누적합이란걸 알았음..
- 처음에는 단순히 for문으로 풀었다가 시간초과
- 누적합 
=> solved 파괴되지 않은 건물 - 43.39ms 217mb

Baekjoon/스타트택시/스타트택시_신유진.java
#92 
- 중하
- 4시간 풀었음.
- 문제는 어렵지 않았으나 예외적인 부분을 잡는다고 오래 걸림.
- “모든 출발지와 목적지는 빈칸이고, 모든 출발지는 서로 다르며, 각 손님의 출발지와 목적지는 다르다.”
→ 현 승객의 출발지와 다른 승객의 목적지가 같을 수 있다.
- BFS, 구현, 정렬
1. 손님의 출발지는 map에 number 저장, 목적지는 따로 목적지 배열에 저장
2. 손님 태우기
1. 현재 위치와 손님이 같은 위치에 있다면 바로 손님 데려다 주기
2. 아니라면 최단 경로인 승객 태우기(findPoint)
1. BFS로 탐색하면서 승객을 찾는다면 우선순위 큐에 넣음
2. 그 중 행이 작고 같으면 열이 작은 것을 하나 빼서 해당 승객을 태움. targetNum에 해당 번호를 넣음.
3. 손님 데려다 주기
1. 아직 연료가 남아있다면 BFS로 탐색하면서 해당 손님의 목적지까지 데려다줌.
=> solved 스타트 택시 - 180ms 23020kb

Baekjoon/욕심쟁이판다/욕심쟁이판다_신유진.java
#90 
- 보통
- 일반적인 dfs에서 max값 비교하는 로직 추가
- 시작 위치부터 더 큰 값들을 탐색하면서 dfs의 반환값과 현재 위치에 저장된 값을 비교하면서 저장
=> solved 욕심쟁이판다 - 480ms 37220kb

Baekjoon/친구네트워크/친구네트워크_심종한.java
#2 
친구의 총합 저장하는 방법만 떠올리면 해결되는 것 같아요
- 유니온-파인드
=> solved 친구네트워크 476ms 58520kb

Programmers/디스크컨트롤러/디스크컨트롤러_심종한.java
#3 
문제를 제대로 읽지 않아 시간이 좀 걸림
- 구현
=> solved 디스크컨트롤러 - 2.72ms, 79.6MB

Baekjoon/색종이붙이기/색종이붙이기_심종한.java
=> solved 색종이붙이기 - 136ms 16560kb

Programmers/파괴되지않은건물/파괴되지않은건물_심종한.java
#89 
입력 범위를 처음에 생각하지 않아 최적화가 필요했음
- 2차원 IMOS 알고리즘 사용하여 누적합 계산
=> solved 파괴되지않은건물 - 49.88ms 211mb

Programmers/디스크컨트롤러/김범규_디스크컨트롤러.js
#3 
정렬 후 우선순위대로 풀면 되는문제
선 정렬 -> 중간도 정렬!
=> solved 디스크컨트롤러 7.37ms 36.6mb

Baekjoon/색종이붙이기/김범규_색종이붙이기.java
#4 
생각이 어려운문제
색종이를 붙였다 떼었다하는 dfs + 백트래킹을 활용하였습니다.
=> solved 색종이붙이기 208ms 24556kb

Baekjoon/친구네트워크/친구네트워크_김훈민.java
#2 
아이디어를 생각해내는 것은 쉬웠으나, union find 자료구조를 어떻게 사용해야 깔끔하게 해결될지 고민이 되었다.
크게 3가지 자료구조를 사용해서 해결했다.
- Union Find 자료구조를 활용하기 위한 Parents 배열
- 부모의 인덱스를 가리키는 역할
- 사람의 이름을 Key로 갖는 Hash Map
- 해당 사람이 몇번째 index를 갖는지 바로 찾을 수 있게 하기 위해 사용
- 현재 network에 몇명의 사람이 연결되어있는지 저장하는 배열
- 부모의 idx에 몇명의 사람이 포함되어있는지 확인하는 용도
가독성 좋은 다른 방법이 있을까요?
=> solved 친구네트워크 - 444ms 59672kb

Programmers/디스크컨트롤러/디스크컨트롤러_김훈민.java
#3 
쉽다고 생각했는데 생각보다 난이도 있었던 문제였습니다.
우선순위 큐를 이용해 조건에 맞는 작업을 빼올 수 있도록 정렬해두고
시간순으로 정렬된 객체를 이용해 다음 우선순위 큐에 넣을 작업을 지정해주어 해결했습니다.
없습니다!
=> solved 디스크컨트롤러 - 4.23ms 87.8mb

Programmers/파괴되지않은건물/허승경_파괴되지않은건물.java
#89 
단순한 구현문제로 풀었다가 효율성 테스트에서 시간초과가 났습니다.
누적합 적용후 다시 풀었는데, 문제의 조건을 잘 확인해야할듯합니다.
- 누적합
- 범위 확인하기
=> solved 파괴되지않은건물 54.48ms 221mb

Baekjoon/욕심쟁이판다/욕심쟁이판다_허승경.java
#90 
처음에 백트래킹 문제인 줄 알고 풀었다가 시간초과가 났습니다.
dp에 뭘 저장하는지 생각하는게 어려운것같습니다.
- dp
=> solved 욕심쟁이판다 428ms 36.996mb

Baekjoon/욕심쟁이판다/욕심쟁이판다_김수빈.java
#90 
어려웠다. 항상 dfs랑 dp는 어렵다 d가 들어가면 나한텐 어렵나보다
dp는 점화식 도출하는게 어렵고 dfs는 재귀적 구조로 짤때 return 값을 어디로 둬야할지 아직 초보자 같은 마인드...
- dp, dfs
=> solved 욕심쟁이 판다 - 732ms 71784kb

Programmers/파괴되지않은건물/파괴되지않은건물_김수빈.java
#89
누적합이란 개념을 몰라서 도움을 받아서 풀었다.
- 누적합 및 차이배열
=> unsolved 파괴되지 않은 건물 - 63.62ms, 219mb

Baekjoon/스타트택시/스타트택시_김수빈.java
=> solved 스타트택시 - 324ms 40804kb

Programmers/파일명정렬/파일명정렬.java
#93 파일명 정렬
뭔가 의사코드를 이렇게 빠르게 적은 게 오랜만이어서 행복했습니다.
- 문자열 파싱
=> solved 파일명 정렬 - 39.90ms 96.2mb

Baekjoon/욕심쟁이판다/욕심쟁이판다_옥수빈.java
=> solved 욕심쟁이 판다 - 472ms 64.076mb

Programmers/부대복귀/부대복귀_김민규.java
#1 
간선을 활용한 BFS는 너무 오랜만이어서 구현 방법을 좀 헤맸습니다. 거리가 1인 다익스트라 형태로 해결했고 좋은 문제라고 생각이 들었습니다.
- 간선 가중치가 모두 1인 최단거리 -> BFS구나 -> 근데 간선 정보만 있다? -> 간선 배열을 활용해서 dijk을 돌리자
- dest 부터 source로 역추적 돌리면 모든 최단거리가 나오겠다. 라고생각해서 풀었습니다.
=> solved 부대복귀 - 253.05ms 197mb

Programmers/디스크컨트롤러/디스크컨트롤러_김민규.java
#3 
정렬문제 + 디스크가 비어있을 때 동작을 파악하지 못하면 많이 어려운 문제인 것 같습니다.
처음에 그냥 구현하고, 검색을 잠깐해서 좀 찜찜하기 때문에 다시 풀어볼 계획입니다.
- pq
=> solved 디스크컨트롤러 - 3.79ms 72.1mb

Baekjoon/색종이붙이기/색종이붙이기_김민규.java
#4 
어려웠습니다.
오랜만에 백트래킹이라 생각방향도 어려웠고, 처음에 for문 중첩해서 풀다가 처리할게 너무 많아지는 것 같아 포기했습니다.
- 백트래킹, pruning
=> solved 색종이붙이기 - 208ms 23704kb

Programmers/파괴되지않은건물/파괴되지않은건물_김민규.java
#89 
어려웠습니다. 효율성검사때문에 누적합인 건 알았지만 어떻게 접근해야하는지 떠올리지 못했습니다.
- IMOS 법을 사용해 해결했습니다.
=> solved 파괴되지않은건물 - 49.90 ms 210 MB

Baekjoon/욕심쟁이판다/욕심쟁이판다_김민규.java
#90 
무난했습니다. 백트래킹을 좀 더 깊게 고민할수있었던 문제
- 시작 지점에서 출발할때의 최장거리를 dp배열에 저장해두고, 방문했을때 항상 최대값이 존재하게 해서 방문 == 최장거리 저장으로 조건을 맞추면 생각하기 편해지는 것 같습니다.
=> solved 욕심쟁이판다 - 480ms	37248kb

Programmers/부대복귀/부대복귀_박은정.java
#1 
- 다익스트라 : 한 정점(destination) 다른 모든 정점들(sources)까지 거리 
=> solved 부대복귀-0ms 0mb

Baekjoon/친구네트워크/친구네트워크_박은정.java
#2 
- 중간
- union find + 각 집합의 루트 노드 번호에 각 집합의 크기를 저장하기
=> solved 친구네트워크 1300ms 72296kb

Programmers/디스크컨트롤러/디스크컨트롤러_박은정.java
=> solved 디스크컨트롤러 0ms 0mb

Programmers/파괴되지않은건물/파괴되지않은건물_박은정.java
#89 
어려웠다
- 누적합 : 누적합이 구해지는 과정에 대한 이해 
=> unsolved 파괴되지않은건물 - 0ms 0mb

Baekjoon/욕심쟁이판다/욕심쟁이판다_박은정.java
=> solved 욕심쟁이판다 - 484ms 37272kb

Programmers/아이템줍기/아이템줍기_박은정.java
#91 
어려웠다
- 테두리를 구분하는 방법
- ㄷ 모양을 처리하는 방법 
=> solved 아이템줍기 - 0ms 0mb

Programmers/파괴되지않은건물/파괴되지않은건물_박단비.py
=> solved 파괴되지않은건물 - 931.54ms 143mb

Baekjoon/욕심쟁이판다/욕심쟁이판다_박단비.py
=> solved 욕심쟁이판다 - 768ms 52144kb

Programmers/아이템줍기/아이템줍기_박단비.py
=> solved 아이템줍기 - 1.40ms 10.5mb

Baekjoon/스타트택시/스타트택시_박단비.py
=> solved 스타트택시 - 316ms 35076kb

Programmers/아이템줍기/허승경_아이템줍기.java
=> solved 아이템줍기 1.44ms 89.2mb

Programmers/파일명정렬/파일명정렬_박단비.py
=> solved 파일명정렬 - 2.74ms 10.2mb

Programmers/파일명정렬/파일명정렬_허승경.java
#93 
문제에서 제시된 조건을 구현하면 돼서 쉽게 느껴졌습니다.
그런데 최적의 코드인지는 고민해봐야할 것 같습니다
-  조건에 따른 우선순위 정렬
=> solved 파일명정렬 21.41ms 91.9mb

Baekjoon/욕심쟁이판다/욕심쟁이판다_심종한.java
=> solved 욕심쟁이판다 - 412ms 67360kb

Programmers/아이템줍기/아이템줍기_심종한.java
#91 
아이디어가 필요했음
- 좌표 2배
- 모서리만 탐색하도록 제한
=> solved 아이템줍기 - 0.61ms 82.4MB

Baekjoon/스타트택시/스타트택시_심종한.java
=> solved 스타트택시 - 984ms 298100kb

Programmers/파일명정렬/파일명정렬_심종한.java
#93 
문자열 관련 함수를 새로 알게 되었습니다
- 정렬만 잘 구현
=> solved 파일명정렬 4.79ms 92.5MB

Baekjoon/뱀/뱀_심종한.java
=> solved 뱀 - 76ms 12124kb

Programmers/파고되지않은건물/파괴되지않은건물_김훈민.java
#89 
아이디어 떠올리는건 쉬웠는데 생각보다 구현이 어려웠다.
인덱스 잘못잡으면 바로 범위를 벗어나서 힘들었다.
누적합을 이용해 빠르게 계산해주는 것이 포인트
없습니다!
=> solved 파괴되지않은건물 - 48.31ms, 210MB

Baekjoon/욕심쟁이판다/욕심쟁이판다_김훈민.java
#90 
처음 BFS로 접근했을때 구현이 까다롭다는 생각이 들어서 위상정렬로 변경해 해결했다.
BFS로 풀다 구현이 까다로워 위상정렬로 변경하여 풀었다.
없습니다.
=> solved 욕심쟁이판다 - 496ms, 53556kb

Programmers/아이템줍기/아이템줍기_김훈민.java
#91
쉬워보였으나 엣지케이스들이 있기 때문에 한번 더 생각해주어야 하는 좋은 문제!
bfs를 돌릴때 모서리가 제대로 체크 안되는 문제 -> 8방향 bfs로 해결
모서리와 변만 타고 이동해야하는 문제 -> 좌표 size를 2배로 늘려해서 해결
없습니다
=> solved 아이템줍기 - 11.11ms, 72.8mb

Baekjoon/스타트택시/스타트택시_김훈민.java
#92 
난이도는 쉬웠는데 코드가 깔끔하지 않아서 아쉽다
bfs를 활용해서 탐색을 해주는데, 어떤 고객이 우선순위가 높은지 잘 판단해주어야한다.
=> solved 스타트택시 - 148ms, 18068kb

Programmers/파일명정렬/파일명정렬_김훈민.java
#93 
조건에 맞추어서 비교만 해주면 되기 때문에 비교적 쉬웠다
조건만 잘 확인해주면 된다
없습니다
=> solved 파일명정렬 - 34.97ms, 75.8MB

Baekjoon/뱀/뱀_박주빈.cpp
#177 
적당한 난이도였습니다.
꼬리를 제거하거나 머리를 추가하는 head, tail의 push, pop이 필요하기 때문에
deque를 사용하여 구현하였습니다.
- Deque
없습니다.
=> solved 뱀 - 0ms 2064kb

Programmers/프렌즈4블록/프렌즈4블록_박주빈.cpp
#178 
적당한 난이도였습니다.
1. 2x2블록을 찾고 -> 2. 따로 저장해 뒀다 한번에 삭제 -> 3. 삭제로 생긴 빈 공간을 메꿈
과정을 그대로 구현하였습니다.
- 구현
- 검사 방향
없습니다.
=> solved 프렌즈4블록 - 1.84ms 4.21mb

Baekjoon/타일채우기/타일채우기_박주빈.cpp
#179 
적당한 난이도였습니다.
점화식만 잘 세우면 금방 풀 것 같았는데, 특수 케이스를 생각하는데 시간이 조금 걸렸습니다.
- Dp
없습니다.
=> solved 타일채우기 - 0ms 2020kb

Programmers/오픈채팅방/오픈채팅방_박주빈.cpp
#180 
쉬운 편이었습니다.
Map 자료구조를 사용할 줄만 알면 그대로 구현하면 되는 문제입니다.
- Map
없습니다.
=> solved 오픈채팅방 - 306.31ms, 43.8mb

Baekjoon/물통/물통_박주빈.cpp
#181
적당한 난이도였습니다.
모든 경우의 수가 200 * 200 * 200가지이기 때문에 dfs로 모든 경우의 수를 돌렸습니다.
visit 배열을 만들어 중복계산을 처리했습니다.
- dfs
없습니다.
=> solved 물통 - 0ms 9956kb

Baekjoon/뱀/뱀_김수빈.java
#177
쉬웠는데 몸상태가 나빠서 풀지 못함... 다시 풀어볼 예정
- 큐
=> unsolved 뱀

Programmers/프렌즈4블록/프렌즈4블록_김수빈.java
=> solved 프렌즈4블록 - 1.15ms 87.5mb

Programmers/오픈채팅방/오픈채팅방_김수빈.java
=> solved 오픈채팅방 - 118.52ms, 176MB

Baekjoon/물통/물통_김수빈.java
=> solved 물통 - 128ms 23640kb

Baekjoon/타일채우기/타일채우기_신유진.java
#179 
- 어려웠음
- DP인 것은 바로 알았으나 점화식을 못 찾음.
- 단순히 곱했을 때의 반복되는 모형과 매번 새로운 모형이 만들어질 수 있는 것이 있음. 
- DP
- dp[N] = ( dp[N - 2] * dp[2] ) + ( dp[N - 4] * 2 ) + ( dp[N - 6] * 2) + ... + ( dp[0] * 2 )
=> solved 타일채우기 - 100ms 14264kb

Programmers/프렌즈4블록/프렌즈4블록_신유진.java
#178 
- 그냥 구현만 잘하면 되었기에 어렵지는 않았으나 코드가 더러워져서 이게 맞나…? 의문이 들면서 풀었음.
- 구현
1. 삭제할 수 있는 블록이 있을 때까지 계속 findBlock함수 호출
1. findBlock 의 결과값이 true라면 삭제할 블록이 있다는 의미이기 때문에 removeBlock 함수 호출
2. false라면 삭제할 수 있는 블록이 없다는 의미이므로 종료 후 결과값 출력
- findBlock 함수 → 2×2 블록 찾기
- `removeBlock = fasle;` 세팅 → 지울 수 있는 블록이 있는지 저장
- 2중 for문으로 board의 값을 가로 2칸, 세로2칸씩 블록을 확인하면서 빈 공간이 아니면서(”-”) 4칸이 모두 같은 값이라면 `removeBlock = true`로 변경. → 함수는 true 반환
- 지울 수 있는 값이 아니라면 계속 다음 위치 탐색. 하나도 지울 수 있는 블록이 없다면 함수 false 반환
- removeBlock → 블록 삭제 및 아래로 내리기
- 기존 블록 중 살아남은 블록만 리스트에 저장
- 해당 블록들을 for문을 사용해서 리스트의 값들을 아래쪽부터 채우고, 남은 공간은 '-'으로 저장 
=> solved 프렌즈4블록 - 100ms 14264mb

Baekjoon/색종이붙이기/색종이붙이기_주혜련.java
#4 
보통
- 백트래킹
- 색종이 종류 당 5개씩(문제를 잘 읽자)
=> solved 색종이붙이기 - 320ms 16792kb

Programmers/파괴되지않은건물/파괴되지않은건물_주혜련.cpp
=> solved 파괴되지않은건물 29.10ms 119mb

Baekjoon/욕심쟁이판다/욕심쟁이판다_주혜련.java
=> solved 욕심쟁이판다 - 444ms 37004kb

Programmers/아이템줍기/아이템줍기_주혜련.cpp
#91 
어려웠다
- 바깥 테두리 0을 기준으로 bfs
- 이때 좌표를 2배 해야하는게 포인트였는데, 못찾고 힌트보고 풀었다
=> solved 아이템줍기 - 0.51ms 4.14kb

Baekjoon/스타트택시/스타트택시_주혜련.cpp
=> solved 스타트택시 - 0ms 2028kb

Programmers/파일명정렬/파일명정렬_주혜련.cpp
=> solved 파일명정렬 - 0.97ms 3.84mb

Baekjoon/뱀/뱀_주혜련.cpp
=> solved 뱀 - 0ms 1268kb

Programmers/프렌즈4블록/프렌즈4블록_주혜련.cpp
=> solved 프렌즈4블록 - 0.34ms 4.01mb

Baekjoon/타일채우기/타일채우기_주혜련.java
=> solved 타일채우기 - 104ms 14180kb

Programmers/오픈채팅방/오픈채팅방_주혜련.cpp
=> solved 오픈채팅방 - 118.85ms 54.2mb

Baekjoon/뱀/뱀_박단비.py
=> solved 뱀 - 64ms 34992kb

Programmers/프렌즈4블록/프렌즈4블록_박단비.py
=> solved 프렌즈4블록 - 618.06ms 9.36mb

Baekjoon/스타트택시/스타트택시_박은정.java
=> solved 스타트택시 - 236ms 235876kb

Programmers/파일명정렬/파일명정렬_박은정.java
=> unsolved 파일명정렬 - 0ms 0mb

Baekjoon/뱀/뱀_박은정.java
#177 
- 구현 : 뱀 머리, 몸, 방향 정보 관리. 종료 조건 관리
=> sovled 뱀 - 108ms 14356kb

Programmers/프렌즈4블록/박은정_프렌즈4블록.java
=> sovled 프렌즈4블록 0ms 0mb

Baekjoon/타일채우기/박은정_타일채우기.java
=> unsolved 타일채우기 - 0ms 0mb

Programmers/오픈채팅방/오픈채팅방_박은정.java
=> solved 오픈채팅방 - 0ms 0mb

Programmers/프렌즈4블록/프렌즈4블록_허승경.java
#178 
문제 있는 걸 그대로 구현해서 쉬웠습니다.
효율성을 생각 안해서 한 번 최적화 해야 할 풀이입니다.
- 구현
- 겹치는 블록 중복처리 잘하기
=> solved 프렌즈4블록 22.22ms 101mb

Programmers/오픈채팅방/오픈채팅방_허승경.java
=> solved 오픈채팅방 133.65ms 187mb

Programmers/부대복귀/부대복귀_최지수.java
=> solved 부대복귀 - 144.01ms 181MB

Baekjoon/친구네트워크/친구네트워크_최지수.txt
#2 
괜찮았습니다.
union find + 가장 조상의 자식 수만 업데이트해주면 되었습니다.
=> solved 친구네트워크 - 968ms 74784KB

Programmers/디스크컨트롤러/디스크컨트롤러_최지수.java
#3 
괜찮았습니다.
정렬과 우선순위 큐를 사용하면 간단하게 풀렸습니다.
=> solved 디스크컨트롤러 - 3.82ms 86.5MB

Programmers/파괴되지않은건물/파괴되지않은건물_최지수.java
=> solved 파괴되지않은건물 - 58.91ms 212MB

Baekjoon/욕심쟁이판다/욕심쟁이판다_최지수.java
#90 
괜찮았습니다.
메모이제이션 비슷하게 풀었습니다.
=> solved 욕심쟁이판다 - 356ms 59960KB

Programmers/아이템줍기/아이템줍기_최지수.txt
#91 
괜찮았습니다.
틈을 확인하기 위해 배열의 크기를 두배로 늘려야 한다는 아이디어가 나와야 했습니다.
=> solved 아이템줍기 - 2.54ms 73.1MB

Baekjoon/스타트택시/스타트택시_최지수.java, Programmers/파일명정렬/파일명정렬_최지수.java
#93 
괜찮았습니다.
정규식을 잘 외워둬야 할 거 같습니다.. 매번 헷갈리네요...
=> solved 파일명정렬 - 19.79ms 75.4MB

Baekjoon/뱀/뱀_최지수.java, Baekjoon/스타트택시/스타트택시_최지수.java, Programmers/파일명정렬/파일명정렬_최지수.java
#177 
괜찮았습니다.
덱의 push pop peek poll의 방향만 안 헷갈리면 되는 문제 같습니다.
=> solved 뱀 - 72ms 12080KB

Programmers/프렌즈4블록/프렌즈4블록_최지수.java
#178 
좀 더 객체지향적이고 효율적으로 푸는 방법이 궁금합니다.
linkedList로 줄마다 담아두고 빼는 방식으로 했습니다.
=> solved 프렌즈4블록 - 19.11ms 84.2MB

Baekjoon/타일채우기/타일채우기_최지수.java
#179 
dp가 싫어요...
4까지는 계산을 했는데, 6부터 이전 기수의 조합끼리는 만들어지지 않는 특수 조합이 2개라는 건 확신하기 어려웠습니다.
이런 걸 확신을 가지고 풀려면 어떻게 접근을 해야하나요?
dp
=> solved 타일채우기 - 64ms 11448KB

Programmers/오픈채팅방/오픈채팅방_최지수.java
=> solved 오픈채팅방 - 156ms 174MB

Baekjoon/뱀/뱀_김범규.java
#177 
구현이라 좀 생각하는 문제, 구현 자체는 괜찮았습니다.
hash를 통한 명령어 검색
=> solved 뱀 120ms 14792kb

Programmers/프렌즈4블록/프렌즈4블록_김범규.js
#178 
some의 사용법을 잘 몰라서 참고 자료를 찾아보았습니다..
1. 가로(행)에서  0이 없는 경우 정렬이 필요없다.
2. 파괴된 블록을 바로 건드리면 결과에 이상이 있으므로, 따로 저장하여 마지막에 한번에 처리한다.
=> solved 프렌즈4블록 233.18ms 40.7mb

Baekjoon/타일채우기/타일채우기_김범규.java
#179 
점화식만 세우면 괜찮은 문제...
점화식 잘 세우기
=> solved 타일채우기 104ms 14156kb

Programmers/오픈채팅방/오픈채팅방_김범규.js
=> solved 오픈채팅방 320.07ms 92.6MB

Baekjoon/물통/물통_김범규.java
#181 
dfs를 활용
dfs 활용하여 물통을 비우거나 채울 수 있는 경우의 수를 계속 탐색한다.
=> solved 물통 136ms 47008kb

Programmers/오픈채팅방/오픈채팅방_박단비.py
=> solved 오픈채팅방 - 153.31ms 41.6mb

Baekjoon/물통/물통_박단비.py
=> solved 물통 - 60ms 35028kb

Baekjoon/물통/물통_허승경.java
#181 
처음에는 주어진 테스트케이스대로 구현했다가 예외가 발생해 탐색으로 돌렸습니다.
- bfs
=> solved 물통 116ms 14.644mb

Baekjoon/물통/물통_최지수.java
#181 
괜찮았습니다.
bfs + 물 붓는 건 그냥 구현했습니다.
=> solved 물통 - 84ms 20628KB

Programmers/징검다리건너기/징검다리건너기_최지수.txt
#265 
효율성 채점이 좀 까다로웠습니다.
이분 탐색 사용했습니다.
다음 체크 시 체크했던 범위만큼 건너뛰어서 == 슬라이딩 윈도우를 사용해서 풀어야 했습니다.
=> solved 징검다리건너기 - 38.29ms 64.5MB

Baekjoon/옥상정원꾸미기/옥상정원꾸미기_최지수.java
#266 
괜찮았습니다.
스택을 잘 이용하면 되는 문제였습니다.
=> solved 옥상정원꾸미기 - 160ms 16108KB

Programmers/불량사용자/불량사용자_최지수.java
=> solved 불량사용자 - 29.31ms 82.5MB

Baekjoon/뱀/뱀_김훈민.java
#177 
간단한 구현 문제
덱을 사용해서 구현을 간단하게 만들었다
없습니다.
=> solved 뱀 - 92ms, 13632kb

Programmers/프렌즈4블록/프렌즈4블록_김훈민.java
#178 
구현 문제 연습을 많이 했던 만큼 쉬웠습니다.
구현 문제는 시간단축을 시키려고 하기보다는 역할별로 메서드를 잘 나누어 최대한 가독성 좋게 구현하는 것이 좋다고 생각해서 그렇게 구현해보았습니다.
따로 없습니다!
=> solved 프렌즈4블록 - 34.91ms, 92.8MB

Baekjoon/타일채우기/타일채우기_김훈민.java
#179 
평소 풀던 타일채우는 dp 문제가 나와서 비교적 쉽게 풀었지만
다른 유형의 dp가 나오면 역시 어려울 것 같다
이런 형태의 문제는 그림을 그려보면서 파악하는게 좋다고 생각한다
이 문제에서는 타일이 특정 길이를 넘을때 불규칙한 문양들이 나오는데 그 부분을 잘잡아내는 것이 중요하다
Down - top 방식으로 구현했는데
Top - down 방식으로 풀수도 있을까요?
=> solved 타일채우기 - 64ms, 11492kb

Programmers/오픈채팅방/오픈채팅방_김훈민.java
#180 
생각보다 굉장히 쉬웠습니다.
예시에서 힌트를 다 주었다고 생각합니다.
Enter uid1234 Muzi 의 형태로 들어오므로 어쨌든 unique한 id가 있으니 map을 사용하면 되겠다고 생각하였습니다.
map을 사용하지 않고도 시간을 단축할 수 있을까요?
=> solved 오픈채팅방 - 124.62ms, 147MB

Baekjoon/물통/물통_김훈민.java
#181 
쉬웠습니다
bfs로 할까하다가 너비를 우선으로 탐색하면 큐 메모리가 터질수도있을 것 같아 dfs로 해결했습니다.
bfs로 풀수도있을까요?
=> solved 물통 - 68ms, 20596kb

Programmers/징검다리건너기/징검다리건너기_박주빈.cpp
#265 
어려웠습니다. 시간 초과가 계속 떠서 포기하고 다른 사람들 풀이를 보았는데,
이분탐색을 사용하는 것을 전혀 떠올리지 못했습니다.
mid 값보다 작은 돌이 연속으로 k개 이상 있으면 false를 반환하고 Start, End 값을 조정
이 과정을 반복하여 Start가 End보다 커지면 Start 값을 반환하는 식으로 최댓값을 찾는 것 같습니다.
- 이분탐색
없습니다.
=> unsolved 징검다리건너기 - 3.33ms 10.4mb

Baekjoon/옥상정원꾸미기/옥상정원꾸미기_박주빈.cpp
#266 
적당한 난이도였습니다. 스택으로 구현하여 풀었습니다.
스택에 있는 빌딩중에 현재 빌딩보다 작은 빌딩은 전부 pop 해준 뒤
스택에 남아있는 개수만큼 누적합을 해줍니다.
이후 새로운 입력을 스택에 push 하는 것을 반복합니다.
- 스택
없습니다.
=> solved 옥상정원꾸미기 - 40ms 2600kb

Programmers/불량사용자/불량사용자_박주빈.cpp
#267 
적당한 난이도였습니다.
id를 비교하는 함수를 만든 후 dfs를 돌렸습니다.
중복이 나올 수 있어서 2중 set을 사용하여 중복을 제거했습니다.
- dfs
- set
없습니다.
=> solved 불량사용자 - 0.69ms 4.22mb

Baekjoon/택배배송/택배배송_박주빈.cpp
#268 
어려웠습니다.
문제는 다익스트라를 이용해야겠다는걸 바로 알아차려서 쉬웠는데,
다익스트라 구현방법을 잊어버려서 많이 헤맸습니다.
- 다익스트라
없습니다.
=> solved 택배배송 - 28ms 5532kb

Programmers/징검다리건너기/징검다리건너기_박단비.py
=> solved 징검다리건너기 - 433.17ms 17.6mb

Baekjoon/옥상정원꾸미기/옥상정원꾸미기_김수빈.java
=> solved 옥상정원 꾸미기 - 256ms 24172kb

Baekjoon/택배배송/택배배송_김수빈.java
#268 
어려웠다 다익스트라... 애증
- 다익스트라
=> unsolved 택배배송 - 472ms, 47456kb

Programmers/거리두기확인하기/거리두기확인하기_김수빈.java
#269 거리 두기 확인하기
쉬웠다 경우의수만 잘 계산하면 오케이
=> solved 거리두기 확인하기 - 0.06ms 92.6mb

Programmers/불량사용자/불량사용자_김수빈.java
#267 불량사용자
3기인가 4기때 풀었던 문제였던 것 같아서 다른 방식으로 풀어보았습니다.
- 조합
- 정규식
=> solved 불량 사용자 - 100.05ms, 105MB

Baekjoon/타일채우기/타일채우기_옥수빈.java
=> solved 타일 채우기 - 112ms 12.852mb

Baekjoon/옥상정원꾸미기/옥상정원꾸미기.py
=> solved 옥상정원꾸미기 - 84ms 36872kb

Programmers/징검다리건너기/징검다리건너기_박은정.java
=> solved 징검다리건너기 - 0ms 0mb

Baekjoon/옥상정원꾸미기/옥상정원꾸미기_박은정.java
=> solved 옥상정원꾸미기 - 264ms 23616kb

Programmers/불량사용자/불량사용자_박은정.java
=> solved 불량사용자 - 0ms 0mb

Programmers/불량사용자/불량사용자_박단비.py
=> solved 불량사용자 - 325.92ms 9.34mb

Baekjoon/택배배송/택배배송_박단비.py
=> solved 택배배송 - 208ms 52284kb

Programmers/징검다리건너기/징검다리건너기_허승경.java
#265 
처음에는 단순구현으로 접근했지만, 일부 테스트케이스에서만 통과가 됐습니다.
건널 수 있는 사람의 최대 수를 구하는 때 범위를 좁혀가면서 탐색해야한다는 걸 알고 이분탐색으로 풀었습니다~
- 이분탐색
=> solved 징검다리건너기 27.17ms 81.8mb

Baekjoon/택배배송/택배배송_허승경.java
#268 
한 정점에서 다른 정점까지/간선마다 가중치 다름/ 최솟값
-> 문제를 읽으며 조건을 정리하니 위에처럼 읽었고 다익스트라문제인걸 확인했습니다.
우선순위큐를 이용해서 문제를 풀었고, 알고 봤더니 두 달전에 4번의 실패끝에 성공한 문제여서 
못 풀었으면 민망할뻔했네요😅
- 문제에서 다익스트라 키워드 찾기
- 우선순위큐
=> solved 택배배송 - 412ms 40.148mb

Programmers/거리두기확인하기/거리두기확인하기_박단비.py
=> solved 거리두기확인하기 - 0.45ms 9.34mb

Baekjoon/택배배송/택배배송_박은정.java
#268 
- 다익스트라 : 초기 MAXfill, 0 초기화, 나중에 최소값이 업데이트 될 수 있음 
=> solved 택배배송 - 39872KB 384ms

Baekjoon/선발명단/선발명단_박은정.java
=> solved 선발명단 - 148ms 15580kb

Baekjoon/테트리스/테트리스_박은정.java
#351 
- 어려웠다
- 테트리스 바닥 모양 
- base 값 정하기 
=> solved 테트리스 - 112ms 14264kb

Programmers/연속펄스부분수열의합/연속펄스부분수열의합_박은정.java
#350 
- 어제 잊고 안 올려서 올립니다
- 
- 누적합 vs 새로 시작
=> solved 연속펄스부분수열의합 - 0ms 0kb

Programmers/후보키/후보키_박은정.java
=> unsolved 후보키- 0ms 0mb

Baekjoon/콘센트/콘센트_박은정.java
=> solved 콘센트 - 15412kb 144ms

Baekjoon/택배배송/택배배송_최지수.java
=> solved 택배배송 - 388ms 40832KB

Baekjoon/옥상정원꾸미기/옥상정원꾸미기_김훈민.java
#266 
단조스택과 뒤에서부터 보는 풀이로 해결했는데, 생각보다 예외처리해주어야 하는 것들이 있어서 쉽지 않았다.
단조스택 + 뒤에서부터 보면 되겠다는 아이디어로 해결
=> solved 옥상정원꾸미기 - 260ms, 23048kb

Programmers/불량사용자/불량사용자_김훈민.java
#267 
쉬웠습니다
문자열 길이나 문자열 리스트의 길이가 길지않아서 dfs 완탐으로 쉽게풀었습니다.
시간복잡도가 커지면 더 효율적인 방법이 필요할것같습니다..
=> solved 불량사용자 - 72.01ms, 109mb

Baekjoon/택배배송/택배배송_김훈민.java
#268 
쉬웠습니다
다익스트라를 사용해서 쉽게 풀었습니다.
다익스트라 말고 다른 풀이법도 있을까요?
=> solved 택배배송 - 348ms, 39892kb

Programmers/거리두기확인하기/거리두기확인하기_김훈민.java
#269 
bfs로 풀려고 했는데 예외케이스가 많아서 풀이를 바꿨습니다.
생각보다 고민을 많이 해야하는 문제였습니다
bfs로 풀 수 있을까요?
=> solved 거리두기확인하기 - 0.18ms, 77MB

Baekjoon/선발명단/선발명단_김훈민.java
#349 
쉬웠습니다!
- dfs를 활용해서 쉽게 풀었습니다
- 완전탐색을 했습니다
시간복잡도를 더 줄일 수 있을까요??
=> solved 선발명단 - 96ms, 12984kb

Programmers/징검다리건너기/징검다리건너기_주혜련.cpp
=> solved 징검다리건너기 - 10.86ms 10.8mb

Baekjoon/옥상정원꾸미기/옥상정원꾸미기_주혜련.cpp
#266 
stack 떠올리기 어려웠음.
풀고나니 LIS와 비슷함
- stack
=> solved 옥상정원꾸미기 -48ms 2336kb

Programmers/불량사용자/불량사용자_주혜련.cpp
#267 
쉬웠다
- 조합, 중복 방지를 위한 hash
=> solved 불량사용자 - 2.77ms 3.64mb

Baekjoon/택배배송/택배배송_주혜련.cpp
=> solved 택배배송 - 68ms 5420kb

Programmers/거리두기확인하기/거리두기확인하기_주혜련.cpp
=> solved 거리두기확인하기 - 0.04ms 4.2mb

Baekjoon/선발명단/선발명단_주혜련.cpp
=> solved 선발명단 - 4ms 2020kb

Programmers/옥상정원꾸미기/옥상정원꾸미기_신유진.java
#266 
- 그냥 for문으로 푼다면 당연히 시간초과가 나기 때문에 DP로 생각했음.
- 이후에 풀이가 생각 안 나서 알고리즘 분류를 보니 스택이었음. 스택으로도 풀이가 생각이 안나서 블로그 참고.
- 스택
1. 스택을 하나 만듦
2. 첫번째 데이터(data[0])는 그냥 스택에 넣음
3. 그 다음 데이터(data[i])부터 스택에 있는 값 검사. 스택의 값을 하나씩 빼면서 현재 데이터(data[i]) 보다 큰 값이 나올 때까지 스택 값 제거. 
4. 결과값(answer)에 현재 스택의 size를 더함. 
5. 스택에 현재 데이터(data[i])를 넣어줌
6. 다시 3번부터 반복.
=> solved 옥상정원꾸미기 - 264ms 24388kb

Baekjoon/택배배송/택배배송_신유진.java
#268 
- 간만에 다익스트라 공부함.
- 문제는 쉬운편
- 다익스트라
1. 최단 거리 테이블(dist)을 무한대로 초기화. 우선순위 큐(pq)를 최단 거리 값을 기준으로 오름차순으로 정렬.
2. 출발 정점인 1을 선택. pq에 new Vertex(1, 0);을 넣음. dist[1] = 0; 으로 세팅
3. pq에서 하나를 뽑은 후 방문하지 않은 정점들 중에서 최단 거리가 가장 짧은 정점에 방문.
4. 해당 정점으로부터 다른 정점으로 갈 수 있는 거리를 이용하여 최단 거리 테이블을 업데이트.
더 짧은 거리를 만들 수 있는 경우에만 업데이트 및 pq에 넣음.
5. 3번과 4번을 반복한다.
=> solved 택배 배송 - 386ms 38088kb

Programmers/징검다리건너기/징검다리건너기_신유진.java
#265 
- 어떻게 풀어야 하는 지는 바로 생각이 났으나 구현을 어떻게 해야할 지를 엄청 고민함.
- 시간 초과 풀이는 알겠으나 효율성까지 통과할 코드는 생각이 안나 블로그 참고
- 이분 탐색
- O(N log M) => 4,000,000
- k개의 연속된 징검다리를 뽑아서(그룹) 그 중 가장 큰 숫자를 고름
- 각 그룹 내에서 뽑은 숫자들 중 가장 작은 값이 answer 값
1. 건널 수 있는 사람 수를 mid로 정함. 
2. 징검다리를 mid명 건널 수 있는 지 검사(canCross 함수)
- stones를 for문으로 탐색하면서 stones의 값이 mid보다 작다면 해당 징검다리는 mid명보다 적게 건너기 가능.
- 이런 징검다리가 연속으로 k개(skip 개수)라면 mid명이 건너는 것은 불가능 하므로 false반환
- mid명이 건널 수 있는 징검다리가 나오면 skip을 다시 0으로 함.
- mid 명이 통과할 수 있다면 true 반환
3. mid명이 통과할 수 있다면 더 많은 사람이 건널 수도 있으므로 left를 mid + 1
4. mid명이 통과할 수 없다면 mid명보다 더 적은 사람이 건널 수 있으므로 right를 mid - 1
=> solved 징검다리건너기 - 38.93ms 82mb

Baekjoon/콘센트/콘센트_신유진.java
#353 
- 문제 자체는 어렵지 않으나 정렬을 어떻게 활용해야 할 지에 대해 오래 걸림.
- 정렬
- 우선 순위 큐
=> solved 콘센트 - 160ms 15396kb

Baekjoon/선발명단/선발명단_박주빈.cpp
#349 
쉬운 편이었습니다.
기본적인 백트래킹 문제로 중복이 없도록 선택해나가면 됩니다.
- 백트래킹
- dfs
없습니다.
=> solved 선발명단 - 0ms 2020kb

Programmers/연속펄스부분수열의합/연속펄스부분수열의합_박주빈.cpp
#350 
어려웠습니다.
문제를 이해하는데 시간이 오래걸렸고 dp를 이용할 생각을 못해서
다른 사람들의 풀이를 참고하여 풀었습니다.
- dp
없습니다.
=> solved 연속펄스부분수열의합 - 4.89ms 24.6mb

Programmers/후보키/후보키_박주빈.cpp
#352 
어려웠습니다.
유일성 체크는 쉽게 됐는데 최소성을 체크하는 과정에서 조합을 이용하여 풀다가
코드가 너무 길어지고 예외처리가 힘들 것 같아서 포기하고 인터넷 검색을 해보니
비트마스킹을 이용하여 풀면 쉽게 해결이 되는 것 같아 다른 사람들의 풀이를 보고 풀었습니다.
- 비트마스킹
없습니다.
=> unsolved 후보키 - 1.45ms 4.2mb

Baekjoon/선발명단/선발명단_박단비.py
=> solved 선발명단 - 104ms 32412kb

Programmers/연속펄스부분수열의합/연속펄스부분수열의합_박단비.py
=> solved 연속펄스부분수열의합 - 768.74ms 114mb

Baekjoon/테트리스/테트리스_김수빈.java
=> solved 테트리스 - 104ms, 14212kb

Programmers/후보키/후보키_김수빈.java
=> unsolved 후보키 - 6.84ms, 87.5MB

Programmers/연속펄스부분수열의합/연속펄스부분수열의합_옥수빈.java
=> solved 연속 펄스 부분 수열의 합 - 30.30ms 140mb

Baekjoon/테트리스/테트리스_박단비.py
=> solved 테트리스 - 36ms 32412kb

Programmers/자물쇠와열쇠/자물쇠와열쇠_박은정.md
#416 
- 쉬웠다
- 구현 (범위 확장, 오른쪽 회전)
=> solved 자물쇠와열쇠 - 0ms 0mb

Baekjoon/선발명단/선발명단_최지수.java
=> solved 선발명단 - 108ms 15084KB

Programmers/연속펄스부분수열의합/연속펄스부분수열의합_최지수.java
=> solved 연속펄스부분수열의합 - 44.75ms 129MB

Programmers/후보키/후보키_최지수.java
#352 
최소성 검증 로직을 효율화하는 방법을 떠올리는 게 어려웠습니다.
단순 구현
이것보다 좀 더 효율적으로 할 수 있는 방법이 분명 있을 거 같은데 여기서 고쳐보자면 뭘 고쳐야 할까요?
=> solved 후보키 - 4.65ms 77.3MB

Baekjoon/콘센트/콘센트_최지수.java
=> solved 콘센트 - 100ms 12528KB

Programmers/거리두기확인하기/거리두기확인하기_허승경.java
#269 
어렵지 않았으나, 대각선 처리할 때 까다로웠습니다.
- 구현 
- 대각선 위치에서 맨해튼 거리 2일때 처리
=> solved 거리두기확인하기 - 1.41ms 93.1ms

Baekjoon/콘센트/콘센트_김훈민.java
#353 
쉬웠습니다
운영체제 프로세스 스케쥴링에서 각 프로세스에 걸리는 시간을 알고 있다면
최적해는 가장 많은 프로세스를 먼저 처리하는 거라고 배웠던 기억이 나서
해당 방법을 적용해보았습니다.
DP로 풀 수 있을까요?
=> solved 콘센트 - 100ms, 12928KB

Programmers/자물쇠와열쇠/자물쇠와열쇠_김훈민.java
#416
생각보다 구현이 쉽지 않았다
구현 문제라서 최대한 메서드르 나누어 디버깅이 쉽도록 했다.
=> solved 자물쇠와열쇠 - 25.07ms, 97MB

Programmers/자물쇠와열쇠/자물쇠와열쇠_신유진.java
#416 
- 어려웠음.
- 풀이조차도 생각이 안나 블로그에서 코드는 보지 않고 풀이방법만 참고
- 구현
- 자물쇠와 열쇠의 크기가 엄청 크지 않아 경우의 수를 다 해보면 됨
- 4번의 회전을 하고 각 회전 후 할 수 있는 모든 이동을 다 해봄.
=> solved 자물쇠와 열쇠 - 2.36ms 75.6mb

Programmers/지게차와크레인/지게차와크레인_신유진.java
#418 
- 문제는 어렵지 않으나 그냥 구현 그 자체 문제라 시간이 오래 걸림..
- 구현
- 지게차 이동과 크레인 이동으로 함수를 나눔
- 지게차 이동
- 물류창고의 외부와 맞닿아있는 4면을 기준으로 첫번째 행, 마지막 행, 첫번째 열, 마지막 열을 각각 탐색
- 해당 위치에서 bfs를 돌면서 옮기는 알파벳 컨테이너이면 list인 changeData에 넣어줌.
- 옮기는 알파벳 컨테이너가 아니면 그냥 넘어감 continue;
- 이미 옮겨진 알파벳 컨테이너이면(’-’) 4방 탐색 후 Queue에 넣음.
- 큐에 데이터가 없을 때까지 탐색.
- 외부와 맞닿아있는 4면을 다 돈 후 changeData의 값들을 돌면서 해당 위치의 data 값을 ‘-’으로 바꿔줌.(컨테이너를 옮겼다는 표시)
- 크레인 이동
- 2중 for문으로 data를 돌면서 옮기는 알파벳 컨테이너이면 바로 ‘-’으로 바꿈.
- requests 크기까지 다 돈 후 남아있는 알파벳의 개수가 answer 결과값.
=> solved 지게차와 크레인 - 48.65ms 95.3mb

Baekjoon/통나무옮기기/통나무옮기기_신유진.java
#417 
- 어떻게 방문 배열을 처리해야 할 지 고민
- 큰 틀은 참고함.
- BFS
=> solved 통나무 옮기기 - 120ms 14804kb

Programmers/자물쇠와열쇠/자물쇠와열쇠_최지수.java
=> solved 자물쇠와열쇠 - 47.32ms 90.4MB

Baekjoon/통나무옮기기/통나무옮기기_최지수.java
=> solved 통나무옮기기 - 104ms 14016KB

Programmers/자물쇠와열쇠/자물쇠와열쇠_박주빈.cpp
#416 
어려웠습니다.
키를 90도씩 회전시키면서 슬라이딩하며 찾는다는 발상까지 닿지 않아서
다른 사람들의 코드를 참조하여 풀었습니다.
배열의 회전 문제는 풀때마다 다 틀리는 것 같습니다...
- 90도 회전
- 배열 확장
없습니다.
=> unsolved 자물쇠와열쇠 - 2.95ms 4.21mb

Baekjoon/통나무옮기기/통나무옮기기_박주빈.cpp
#417 
어려웠습니다.
최소 횟수를 구하는 것이라 bfs를 이용했는데
통나무의 가로모양(ㅡ), 세로모양(ㅣ) 경우에 따라
구현하는데 필요한 요소들이 많아져서 구현이 복잡했습니다.
- bfs
없습니다.
=> solved 통나무옮기기 - 0ms 2032kb

Programmers/지게차와크레인/지게차와크레인_박주빈.cpp
#418 
어려웠습니다.
겉부분만 탐색하는 경우를 짜는데 시간이 좀 걸렸습니다.
- bfs
없습니다.
=> solved 지게차와크레인 - 3.49ms 4.17mb

Baekjoon/전시장/전시장_박주빈.cpp
#420 
적당한 난이도였습니다.
그림을 높이 순서로 정렬한 뒤, i번째 그림을 선택할지 혹은 선택하지 않을지를 고려하여
누적합을 갱신하는 식으로 풀었습니다.
- dp
- 이진탐색
없습니다.
=> solved 전시장 - 240ms 6712kb

Programmers/기둥과보설치/기둥과보설치_박주빈.cpp
#421 
적당한 난이도였습니다.
단순 구현 문제인데 테스크 케이스 일부가 통과되지 않아서
틀린 부분을 찾느라 푸는데 시간은 오래걸렸습니다.
- 구현
없습니다.
=> solved 기둥과보설치 - 1.43ms 4.55mb

Baekjoon/콘센트/콘센트_허승경.java
#353 
생각에 비해 풀이가 단순했던 것 같습니다.
- 정렬
- 우선순위큐
=> solved 콘센트 - 176ms 17.588mb

Programmers/지게차와크레인/지게차와크레인_최지수.java
=> solved 지게차와크레인 - 25.57ms 83.9MB

Baekjoon/전시장/전시장_최지수.java
#420 
dp인데도 쉽게 방법을 떠올릴 수 있어서 좋았습니다.
그래도 dp는 싫네요...
dp, 같은 높이라면 어차피 동시에 채택이 불가하니 제일 값진 것 하나만 두기
이진탐색 <- s 보다 더 작은 그림 찾기
=> solved 전시장 - 500ms 56788KB

Programmers/기둥과보설치/기둥과보설치_주혜련.cpp
=> solved 기둥과보설치 - 15.68ms 4.2mb

Programmers/후보키/후보키_주혜련.cpp
#352 
쉬웠다
- 최소성에서 pick한 원소들을 하나씩 빼보면서 유일성을 만족하면 false 처리
=> solved 후보키 - 1.78ms 4.15mb

Baekjoon/전시장/전시장_주혜련.cpp
#420 
어려웠다
- 그림 i 당 h[i]-S이하의 높이를 가지는 그림들 중 가장 높은 그림들을 limit에 전처리 해야 했음
=> solved 전시장 - 232ms 6708kb

Programmers/자물쇠와열쇠/자물쇠와열쇠_주혜련.cpp
#416 
쉬웠다
- 회전하고 단순 비교
- 자물쇠의 시작점을 [M-1][M-1]~[N-1][N-1]로 잡아야함
=> solved 자물쇠와열쇠 - 0.51ms 4.13mb

Baekjoon/콘센트/콘센트_주혜련.cpp
=> solved 콘센트 - 0ms 2064kb

Baekjoon/테트리스/테트리스_주혜련.cpp
#351 
어려웠다
- 끝까지  설계 다하고 시작했으면, 마지막 높이만 배열에 그냥 넣어서 편하게 풀었을 것 같다
=> solved 테트리스 - 0ms 2028kb

Programmers/기둥과보설치/기둥과보설치_최지수.java
#421 
체크해야할 기둥과 보의 좌표를 계산하는 데서 자꾸 실수가 나와서 시간이 오래 걸렸습니다.
좌표만 잘 신경쓰면 되는 단순 구현인 것 같습니다.
=> solved 기둥과보설치 - 1.38ms 93.4MB

Programmers/후보키/후보키_박단비.py
=> unsolved 후보키 - 6.38ms 9.38mb

Baekjoon/콘센트/콘센트_박단비.py
=> solved 콘센트 - 64ms 34924kb

Programmers/자물쇠와열쇠/좌물쇠와열쇠_박단비.py
=> solved 자물쇠와열쇠 - 462.64ms 9.4mb

Baekjoon/통나무옮기기/통나무옮기기_박단비.py
=> solved 통나무옮기기 - 80ms 35872kb

Programmers/기둥과보설치/기둥과보설치_박단비.py
=> solved 기둥과보설치 - 2846.85ms 9.57mb

Programmers/부대복귀/부대복귀_강민정.java
=> solved 부대복귀 - 248.62ms 198mb

Baekjoon/친구네트워크/친구네트워크_강민정.java
- #2 
- **_union-find_**를 사용해야 한다는 것을 알면 풀 수 있는 문제라서 크게 어렵진 않았어요.
- **_union-find_**
- 수정하면 좋을 부분이 있을까요?
=> solved 친구네트워크 - 860ms 104444kb

Programmers/디스크컨트롤러/디스크컨트롤러_강민정.java
=> solved 디스크컨트롤러 - 3.32ms 84.7mb

Baekjoon/색종이붙이기/색종이붙이기_강민정.java
- #4 
- 어려운편
- 백트래킹
- 다들 어떤 방법으로 푸셨나요?
=> solved 색종이붙이기 - 204ms 22164kb

Programmers/파괴되지않은건물/파괴되지않은건물_강민정.java
=> solved 파괴되지않은건물 - 56.55ms 213mb

Baekjoon/욕심쟁이판다/욕심쟁이판다_강민정.java
- #90 
- 보통
- 메모이제이션과 DFS
- 다들 어떻게 푸셨나요?
=> solved 욕심쟁이판다 - 396ms 40808kb

Programmers/아이템줍기/아이템줍기_강민정.java
=> solved 아이템줍기 - 1.21ms 86.4mb

Programmers/프렌즈4블록/프렌즈4블록_강민정.java
- #178 
- 쉬움
- 모든 좌표를 시작점으로 탐색하고, 2 * 2 크기만큼 비교
- `String[]`을 `char[][]`로 변환
=> solved 프렌즈4블록 - 10.96ms 88.7mb

Baekjoon/타일채우기/타일채우기_강민정.java
=> solved 타일채우기 - 96ms 12872kb

Baekjoon/물통/물통_강민정.java
=> solved 물통 - 100ms 21968kb

Programmers/불량사용자/불량사용자_강민정.java
- #267 
- 보통
- 다른 사람 풀이 보니까 정규 표현식을 쓰더라고요 😂 저는 직접 구현했습니다ㅎ
- 조합, 순열 구현
=> solved 불량사용자 - 25.79ms 75mb

Baekjoon/옥상정원꾸미기/옥상정원꾸미기_강민정.java
=> solved 옥상정원꾸미기 - 240ms 23324kb

Baekjoon/스타트택시/스타트택시_강민정.java
=> solved 스타트택시 - 904ms 294440kb

Programmers/파일명정렬/파일명정렬_강민정.java
- #93 
- 쉬움
- `Comparable`의 `compareTo` 메서드 재정의
=> solved 파일명정렬 - 6.92ms 80.5mb

Programmers/징검다리건너기/징검다리건너기_강민정.java
=> solved 징검다리건너기 - 77.01ms 79.3mb

Baekjoon/택배배송/택배배송_강민정.java
=> solved 택배배송 - 440ms 53524kb

Programmers/거리두기확인하기/거리두기확인하기_강민정.java
=> solved 거리두기확인하기 - 18.67ms 72.8mb

Baekjoon/선발명단/선발명단_강민정.java
=> solved 선발명단 - 104ms 13204kb

Programmers/연속펄스부분수열의합/연속펄스부분수열의합_강민정.java
=> solved 연속펄스부분수열의합 - 13.00ms 129mb

Baekjoon/콘센트/콘센트_강민정.java
- #353 
- 쉬움
- 충전 속도가 오래 걸리는 것부터 우선순위 큐에 넣기
- 수정하면 좋을 부분이 있을까요?
=> solved 콘센트 - 188ms 13848kb

Programmers/자물쇠와열쇠/자물쇠와열쇠_강민정.java
=> solved 자물쇠와열쇠 - 324.32ms 77.1mb

Programmers/지게차와크레인/지게차와크레인_김훈민.java
#418 
많이 풀어본 유형이라서 쉽게 해결했다.
bfs를 쉽게 하기 위해서 실제 배열 사이즈보다 하나 크게 잡아서 bfs를 활용하기 쉽도록 하였다.
=> solved 지게차와크레인 - 38.34ms, 82.1MB

Baekjoon/전시장/전시장_김훈민.java
#420 
아이디어를 떠올리기 쉽지않았다.
이진탐색을 통해서 나보다 작은 그림들중에서 차이가 가장 적게나는 그림을 고른다는 아이디어를 떠올리기 쉽지않았다.
=> solved 전시장 - 1184ms, 98556KB
